# -*- coding: utf-8 -*-
"""MatplotLib.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zqAN_pE-hFQZE6jrEDvWTykGzXvbRf5w

#Line Lib
"""

import numpy as np
from matplotlib import pyplot as plt

x = np.arange(1,11)
x

y = 30*x
y

plt.plot(x,y,color='g',linestyle=':',linewidth=3) #plotting of x,y graph with customization of
plt.title('x is to y')#color green line style: and width of 3
plt.xlabel('x axis')
plt.ylabel('y axis')
plt.show()

#now plotting two lines with grid
z=y*50
z

plt.plot(x,y,color='r',linestyle=':')
plt.plot(y,z)
plt.grid(True)

#drawing of two plots seperately
plt.subplot(1,2,1)# it creating single row, two columns and giving indexes
plt.plot(x,y)
plt.xlabel('x axis of graph 1')
plt.subplot(1,2,2)
plt.xlabel('x axis of graph 2')
plt.plot(y,z)

#drawing of two plots seperately
plt.subplot(2,1,1)# it creating two rows, one column and giving indexes
plt.plot(x,y)
plt.xlabel('x axis of graph 1')
plt.subplot(2,1,2)
plt.xlabel('x axis of graph 2')
plt.plot(y,z)



"""#Bar Plot"""

student = {'prasanth':87,"anuraag":77,"jayanth":67} #creation of vertical bar plot
names=list(student.keys()) #extracting the name keys from the dict
values = list(student.values())#extracting the values from the dict
plt.bar(names,values)
plt.xlabel('names')
plt.ylabel('marks')
plt.title('bar plot')
plt.grid(True)
plt.show()

student = {'prasanth':87,"anuraag":77,"jayanth":67} #creation of horizontal bar plot
names=list(student.keys()) #extracting the name keys from the dict
values = list(student.values())#extracting the values from the dict
plt.barh(names,values,color='green')
plt.xlabel('names')
plt.ylabel('marks')
plt.title('bar plot')
plt.grid(True)
plt.show()



"""#Scatter Plot"""

#scatter plot is used to understand the distribution between twwo numerical entities
x = [10,20,30,40,50,60,70,80,90]
a = [1,2,3,4,5,6,7,8,9]
plt.scatter(x,a)

#bar and line plot in same graph
#scatter plot is used to understand the distribution between twwo numerical entities
x = [10,20,30,40,50,60,70,80,90]
a = [1,2,3,4,5,6,7,8,9]
plt.scatter(x,a)
plt.plot(x,a)

x=[1,2,3,4,5,6,7,8,9]
y=[9,8,7,6,5,4,3,2,1]
plt.scatter(x,y,marker='*',color='r',s=200)
plt.scatter(x,y,marker='*',color='g',s=100)

x=[1,2,3,4,5,6,7,8,9]
y=[9,8,7,6,5,4,3,2,1]
plt.subplot(1,2,1)
plt.scatter(x,y,marker='*',color='r',s=200)
plt.subplot(1,2,2)
plt.scatter(x,y,marker='*',color='g',s=100)

"""#Histogram"""

data = [1,2,3,4,5,6,7,1,2,3]
plt.hist(data)

import numpy as np
from matplotlib import pyplot as plt
array = np.array([i for i in range(100)])
plt.hist(array)

data = [1,2,3,4,5,6,7,1,2,3]
plt.hist(data, color='g',bins =5)

import pandas as pd
iris = pd.read_csv('/content/Iris.csv')
iris.head()

plt.hist(iris['Species'],bins=50)

"""#Box Plot"""

one = [1,2,3,44]
two= [2,3,4,5]
three = [4,5,67,7]
data = list([one,two,three])
plt.boxplot(data)

one = [1,2,3,44]
two= [2,3,4,5]
three = [4,5,67,7]
data = list([one,two,three])
plt.violinplot(data)

fruit = ['apple','orange']
quantity = [12,88]
plt.pie(quantity,labels=fruit)

